# Generated by Django 5.2.8 on 2025-12-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
